#-------------------------------------------------------------------------------------------------------------------
#                                             Server Configuration
#---------------------------------------------------------------------------------------------------------
server:
  port: 8080
  error:
    whitelabel:
      enabled: false


#-------------------------------------------------------------------------------------------------------------------
#                                             Spring Configuration
#-------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/contents/**, /api/boards/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: balon-service
          uri: lb://balon-service
          predicates:
            - Path=/api/saleads/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/boards/**



#-------------------------------------------------------------------------------------------------------------------
#                                             Eureka Configuration
#-------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}