#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Deployment      --------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: service-discovery-server
    name: service-discovery-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-discovery-server
    template:
        metadata:
            labels:
                app: service-discovery-server
        spec:
            containers:
            - name: service-discovery-server
              image: fabioferrero/unitiprog:service-discovery-server

              ports:
                - containerPort: 8761
---
#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Service      -----------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: service-discovery-server
    labels:
        app: service-discovery-server
spec:
    type: LoadBalancer
    ports:
        - port: 8761
          targetPort: 8761
    selector:
        app: service-discovery-server
    
          
          
    