#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Deployment      --------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: rabbitmq
    name: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: rabbitmq:management
                
                  ports:
                      - containerPort: 5672
#                      - containerPort: 15672
---
#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Service      -----------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
    labels:
        app: rabbitmq
spec:
    ports:
#        - name: port1
        - port: 5672
          targetPort: 5672
#        - name: port2
#          port: 15672
#          targetPort: 15672
    selector:
        app: rabbitmq