version: "3"
services:
  db-users:
    container_name: db-users
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - db-users-data:/var/lib/postgresql/data
    networks:
      - opnet
    environment:
      POSTGRES_DB: usersDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  db-contents:
    container_name: db-contents
    image: "postgres"
    ports:
      - "5434:5432"
    volumes:
      - db-contents-data:/var/lib/postgresql/data
    networks:
      - opnet
    environment:
      POSTGRES_DB: contentsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  db-saleads:
    container_name: db-saleads
    image: "postgres"
    ports:
      - "5435:5432"
    volumes:
      - db-saleads-data:/var/lib/postgresql/data
    networks:
      - opnet
    environment:
      POSTGRES_DB: saleadsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db-users
      - db-contents
      - db-saleads
    networks:
      - opnet

  service-discovery-server:
    container_name: service-discovery-server
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    depends_on:
      - db-users
      - db-contents
      - db-saleads
    networks:
      - opnet

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
      - db-users
      - db-contents
      - db-saleads

    networks:
      - opnet

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    networks:
      - network_rabbit

  user-service:
    container_name: user-service
    image: user-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db-users
      - db-contents
      - db-saleads
      - service-discovery-server
      - api-gateway
    networks:
      - opnet

  content-service:
    container_name: content-service
    image: content-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db-users
      - db-contents
      - service-discovery-server
      - api-gateway
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - opnet
      - network_rabbit

  balon-service:
    container_name: balon-service
    image: balon-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db-users
      - db-saleads
      - service-discovery-server
      - api-gateway
    networks:
      - opnet


  telegram-service:
    container_name: telegram-service
    image: telegram-service:latest
    tty: true
    stdin_open: true
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8086:8086"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - network_rabbit

volumes:
  db-users-data:
  db-contents-data:
  db-saleads-data:
  pgadmin-data:
networks:
  opnet:
    driver: bridge
  network_rabbit: