version: "3"
services:
  demotelegramapi:
    container_name: telegram-service
    image: demotelegramapi:latest
    tty: true
    stdin_open: true
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure

#docker-compose build && docker-compose up (-d) || docker-compose run demotelegramapi