#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Deployment      --------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: telegram-service
    name: telegram-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: telegram-service
    template:
        metadata:
            labels:
                app: telegram-service
        spec:
            containers:
                - name: telegram-service
                  image: fabioferrero/unitiprog:telegram-service
                
                  ports:
                      - containerPort: 8086
                  stdin: true
                  tty: true
            restartPolicy: Always
---
#-------------------------------------------------------------------------------------------------------------
#------------------------------------       Service      -----------------------------------------------------
#-------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
    name: telegram-service
    labels:
        app: telegram-service
spec:
    type: LoadBalancer
    ports:
        - port: 8086
          targetPort: 8086
    selector:
        app: telegram-service