#-------------------------------------------------------------------------------------------------------------------
#                                             Server Configuration
#--------------------------------------------------------------------------------------------------------------
server:
  port: 8761
  error:
    whitelabel:
      enabled: false



#-------------------------------------------------------------------------------------------------------------------
#                                             Spring Configuration
#-------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: service-discovery-server



#-------------------------------------------------------------------------------------------------------------------
#                                             Eureka Configuration
#-------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://0.0.0.0:8761/eureka"
